import { Menu, Transition } from "@headlessui/react";
import { CalendarDaysIcon, ChevronDownIcon } from "@heroicons/react/20/solid";
import Head from "next/head";
import React, { Fragment, useState } from "react";
import Header from "../../components/Header";
import DatePicker from "react-datepicker";
import "react-datepicker/dist/react-datepicker.css";
import Trips from "../../components/Trips";
import Book from "../../components/Book";

function classNames(...classes) {
  return classes.filter(Boolean).join(" ");
}

const Places = [
  {
    name: "GARISSA",
  },
  { name: "BANGAL" },
  {
    name: "KANYONYO",
  },
  { name: "KITHIMANI" },
  {
    name: "KITHYOKA",
  },
  { name: "MATUU" },
  {
    name: "MWINGI",
  },
  { name: "NGUNI" },
  {
    name: "UKASI",
  },
  { name: "NAIROBI" },
];
const Destination = [
  {
    name: "--Destination",
  },
  { name: "BANGAL" },
  {
    name: "KANYONYO",
  },
  { name: "KITHIMANI" },
  {
    name: "KITHYOKA",
  },
  { name: "MATUU" },
  {
    name: "MWINGI",
  },
  { name: "NGUNI" },
  {
    name: "UKASI",
  },
  { name: "NAIROBI" },
];

function Bookticket() {
  const getInitialState = () => {
    const place = "GARISSA";
    return place;
  };

  const [place, setPlace] = useState("GARISSA");
  const [destination, setDestination] = useState(getInitialState);

  const handlePlace = (e) => {
    setPlace(e.target.value);
  };

  const handleDestination = (e) => {
    setDestination(e.target.value);
  };

  const [startDate, setStartDate] = useState(new Date());

  return (
    <div>
      <Head>
        <title>Online Bus Services</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="mx-5">
        <div className="flex bg-blue-300 py-1">
          <div className="ml-1 ">
            <select
              className="w-48 border-2 py-1 px-3 rounded-lg justify-between mr-2"
              value={place}
              onChange={handlePlace}
            >
              {Places.map((place) => (
                <option key={place.name} value={place.name}>{place.name}</option>
              ))}
            </select>
          </div>
          <div className="ml-2 ">
            <select
              className="w-48 border-2 py-1 px-3 rounded-lg justify-between mr-2"
              value={destination}
              onChange={handleDestination}
            >
              {Destination.map((place) => (
                <option key={place.name} value={place.name}>{place.name}</option>
              ))}
            </select>
          </div>
          <div className="p-1 border-2 rounded-lg flex divide-x-2 bg-white  divide-gray-400 ">
            <DatePicker
              className="ml-2"
              selected={startDate}
              onChange={(date) => setStartDate(date)}
              dateFormat="dd/M/yyyy"
            />
            <CalendarDaysIcon height="23" className="pl-1" />
          </div>
          <button className="ml-5 bg-red-600 rounded-md px-3 flex justify-between w-28 items-center text-white">
            Lock Trip <ChevronDownIcon height="18" />{" "}
          </button>
          <button className="flex items-center ml-5">
            <label
              htmlFor="disabled-checked-toggle"
              className="inline-flex relative items-center cursor-pointer"
            >
              <input
                type="checkbox"
                defaultValue
                id="disabled-checked-toggle"
                className="sr-only peer"
                defaultChecked
              />
              <div className="w-11 h-6 bg-gray-200 rounded-full peer dark:bg-gray-700 peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-0.5 after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all dark:border-gray-600 peer-checked:bg-blue-600" />
              <span className="ml-3 text-sm text-black font-bold ">
                Highway
              </span>
            </label>
          </button>
        </div>
        <div>
          <Trips />
          <Book value={place} />
        </div>
      </main>
    </div>
  );
}

export default Bookticket;
