import Head from 'next/head';
import React from 'react'
import Header from '../../components/Header';
import Trips from '../../components/Trips';
import Triptest from '../../components/Triptest';

function trip() {
  return (
    <div>
      <Head>
        <title>Online Bus Services</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Triptest/>
    </div>
  );
}

export default trip