import Head from "next/head";
import Image from "next/image";
import Tickets from "../components/Tickets";
import Header from "../components/Header";
import Parcels from "../components/Parcels";
import { format, formatDistance, formatRelative, subDays } from "date-fns";
import { useEffect } from "react";
import Recon from "../components/Recon";
import Reports from "../components/Reports";

export default function Home() {
  const day = format(new Date(), "eeee");
  const date = format(new Date(), "d-M-y");
  const time = format(new Date(), "h:m a");

  return (
    <div className="flex flex-col h-full justify-between">
      {/* <div> */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex w-full">
        <div className="flex flex-col w-full lg:w-9/12">
          <Tickets />
          <Parcels />
          <Recon />
          <Reports />
        </div>
        <div className="hidden lg:flex items-center justify-between">
          <div className="mx-5">
            <p className="font-bold text-2xl text-gray-500">{time}</p>
          </div>
          <div>
            <h2 className="font-bold text-xl text-gray-500">{day}</h2>{" "}
            <p className="italic text-gray-500 text-sm">{date}</p>
          </div>
        </div>
      </main>

      <footer className="flex flex-1 border-t-1 border-gray-100 justify-center items-center ">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by
          <span className="">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
