import Head from "next/head";
import Header from "../components/Header";
import Dashboard from "../components/Dashboard";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div className="flex flex-col h-full justify-between ">
      {/* Page Title */}
      <Head>
        <title>Online Bus Services</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Navigation bar || header bar  */}
      <Header />

      {/* main page content Dashboard */}
      <main className="flex w-full">
        <Dashboard />
      </main>

      {/* footer */}
      <Footer />
    </div>
  );
}
